name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    name: Run Linting, Type Checking, and Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.8.0"

      - name: Install Dependencies
        run: poetry install --with dev

      - name: Run Ruff (Linting)
        run: poetry run ruff check .

      - name: Run mypy (Type Checking)
        run: poetry run mypy .

      - name: Run Tests (pytest)
        run: poetry run pytest --cov=DVSPortal --cov-report=term-missing
